name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 支持手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 设置 QEMU 以支持跨架构
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    # Step 3: 设置 Docker 构建环境
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: 登录 GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    # Step 5: 构建并推送 Docker 镜像到 GHCR
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/arm64
        tags: ghcr.io/${{ github.repository_owner }}/rustdesk-arm64:latest
